In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
url = 'https://gist.githubusercontent.com/ahcamachod/d2efadda3f3833d65da750c64705ac42/raw/80aef6f3bad210d34b67ed85565f039a30e2d9e0/ventas.csv'
df = pd.read_csv(url, sep='#')
df

,fecha_pedido,fecha_envio,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,precio_base,precio_unit_sin_descuento,descuento,precio_unit_venta,cantidad,ventas,ganancia
0,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,35.88,42.24,0.100,38.02,2,76.04,4.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2018-09-30,2018-10-04,Entrega estándar,Raúl González,B2C,Córdoba,Córdoba,Central,Automotriz,Herramientas automotrices,97.34,123.22,0.000,123.22,1,123.22,25.88
8936,2019-11-18,2019-11-22,Entrega estándar,Antonella Vidal,B2B,General Alvear,Mendoza,Cuyo,Automotriz,Herramientas automotrices,223.01,271.97,0.000,271.97,1,271.97,48.96
8937,2019-11-18,2019-11-22,Entrega estándar,Antonella Vidal,B2B,General Alvear,Mendoza,Cuyo,Automotriz,Neumáticos,121.23,140.15,0.000,140.15,5,700.75,94.60
8938,2016-01-22,2016-01-24,Económica,Catalina Rojas,B2C,Neuquén,Neuquén,Patagónica,Materiales de construcción,Iluminación,26.29,31.79,0.100,28.61,3,85.83,6.96
8939,2019-05-05,2019-05-10,Económica,Jorge Molina,B2C,General Roca,Río Negro,Patagónica,Jardinería y paisajismo,Muebles de exterior,351.36,413.37,0.000,413.37,2,826.74,124.02

In [4]:
df.columns

Index(['fecha_pedido', 'fecha_envio', 'modo_envio', 'nombre_cliente',
       'segmento_cliente', 'ciudad', 'provincia', 'region', 'departamento',
       'tipo_producto', 'precio_base', 'precio_unit_sin_descuento',
       'descuento', 'precio_unit_venta', 'cantidad', 'ventas', 'ganancia'],
      dtype='object')

In [5]:
df_01 = df[['fecha_pedido', 'modo_envio', 'nombre_cliente', 'segmento_cliente', 'ciudad', 'provincia', 'region', 'departamento', 'tipo_producto', 'ventas', 'cantidad', 'ganancia']]
df_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.2+ KB

In [6]:
df_01['fecha_pedido'] = pd.to_datetime(df_01['fecha_pedido'], format='%Y-%m-%d')
df_01

C:\Users\wmalv\AppData\Local\Temp\ipykernel_35720\218206227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_01['fecha_pedido'] = pd.to_datetime(df_01['fecha_pedido'], format='%Y-%m-%d')

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29
2,2018-06-13,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,49.72,2,11.68
3,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,3255.75,5,-651.15
4,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,76.04,2,4.28
...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2018-09-30,Entrega estándar,Raúl González,B2C,Córdoba,Córdoba,Central,Automotriz,Herramientas automotrices,123.22,1,25.88
8936,2019-11-18,Entrega estándar,Antonella Vidal,B2B,General Alvear,Mendoza,Cuyo,Automotriz,Herramientas automotrices,271.97,1,48.96
8937,2019-11-18,Entrega estándar,Antonella Vidal,B2B,General Alvear,Mendoza,Cuyo,Automotriz,Neumáticos,700.75,5,94.60
8938,2016-01-22,Económica,Catalina Rojas,B2C,Neuquén,Neuquén,Patagónica,Materiales de construcción,Iluminación,85.83,3,6.96
8939,2019-05-05,Económica,Jorge Molina,B2C,General Roca,Río Negro,Patagónica,Jardinería y paisajismo,Muebles de exterior,826.74,2,124.02

In [7]:
df_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.2+ KB

# Mision 1: Equipo Ventas
>
> Se necesita construir una visualizacion para indicar __los 10 principales clientes por total de ventas__.
---

In [8]:
clientes = df_01.groupby('nombre_cliente')['ventas'].sum().sort_values(ascending=False).copy().round(2).head(10)     ## sum().nlargest(10)
clientes = clientes.reset_index()
clientes

      nombre_cliente    ventas
0    Víctor Carrasco  73370.61
1        Brisa Rojas  68868.11
2       Mateo Vargas  62749.75
3      Vicente Rojas  59544.11
4        Laura Rojas  51398.87
5         Lucía Díaz  48178.99
6   Cristina Barrios  47610.80
7  Alejandro Sánchez  43769.25
8      Pamela Huerta  42354.19
9     Carlos Sánchez  41238.81

In [9]:
clientes.columns = ['Clientes', 'Ventas']
clientes['Ranking'] = clientes['Ventas'].rank(ascending=False).astype(int)
clientes.set_index('Ranking', inplace=True)
clientes

                  Clientes    Ventas
Ranking
1          Víctor Carrasco  73370.61
2              Brisa Rojas  68868.11
3             Mateo Vargas  62749.75
4            Vicente Rojas  59544.11
5              Laura Rojas  51398.87
6               Lucía Díaz  48178.99
7         Cristina Barrios  47610.80
8        Alejandro Sánchez  43769.25
9            Pamela Huerta  42354.19
10          Carlos Sánchez  41238.81

In [10]:
estilo_01 = clientes.style
estilo_01

In [11]:
estilo_01.format({'Ventas': '${:,.2f}'})
estilo_01

### Ejemplo 1

In [12]:
df_libros = pd.read_csv('https://gist.githubusercontent.com/ahcamachod/52da15c2bbb31e4270b5c267dd051473/raw/62c366878ebd4be2ec899836413c8d1f3e116c01/tienda_libros.csv')
df_libros.sample(5)

,pais,id_cliente,fecha_pedido,fecha_llegada,tipo_compra,numero_pedido,tamano_paquete,unidades,costo_empacado,costo_envio,tipo_descuento,categoria,tipo_consumo,tipo_cliente,costo_producto
23893,Colombia,217563390,2006-02-10,2006-02-26,Normal,98086121,Paquete pequeño,1,2.0,5.99,Sin descuento,Libro,Alto Consumo,B2C,7.99
2060,Chile,463804554,2007-09-24,2007-10-15,Normal,98083947,Paquete grande,1,1.0,3.10,Sin descuento,CD,Bajo consumo,B2C,4.10
14715,Ecuador,111962928,2009-01-08,2009-01-29,Normal,98082201,Paquete pequeño,2,1.0,6.00,Fecha especial,Libro,Bajo consumo,B2C,7.00
24457,Perú,514136954,2006-08-16,2006-08-31,Normal,98085451,Paquete pequeño,1,2.0,5.61,Sin descuento,Libro,Alto Consumo,B2B,7.61
13669,Venezuela,378428659,2003-03-31,2003-04-18,Normal,98089946,Paquete grande,2,2.0,4.55,Cyber Monday,Colección,Alto Consumo,B2C,6.55

In [13]:
# Agrupar y sumar las unidades por país, ordenar los valores
df_paises = df_libros.groupby(['pais'])['unidades'].sum().nlargest(9).copy()
df_paises = df_paises.reset_index()

# Cambiar los nombres de las columnas y ajustar el ranking
df_paises.columns = ['País', 'Unidades pedidas']
df_paises['Rank'] = df_paises.index + 1
df_paises.set_index('Rank', inplace=True)
df_paises

           País  Unidades pedidas
Rank
1     Argentina              5591
2       Ecuador              5566
3      Paraguay              5564
4          Perú              5550
5     Venezuela              5529
6      Colombia              5504
7        Brasil              5473
8       Uruguay              5377
9         Chile              5304

In [14]:
s_pais = df_paises.style
# Formatear el texto para agregar la unidad de medida
s_pais = s_pais.format({'Unidades pedidas': '{} prod'})
s_pais

# Mision 2: Equipo Comercial
>
> Se necesita construir una visualizacion que permita asociar el __total de ventas y el total de lucros por tipo de producto__.
---

In [15]:
product_type = df_01.groupby(['tipo_producto'])[['ventas','ganancia']].sum().round(2).copy()
product_type = product_type.reset_index()
product_type.columns = ['Tipo Producto', 'Ventas', 'Ganancia']
product_type.set_index('Tipo Producto', inplace=True)
product_type

                                 Ventas  Ganancia
Tipo Producto
Brotes                          8811.32   1381.42
Decoración de jardín           82680.08   9939.43
Equipos de limpieza           542304.58   8724.39
Fertilizantes                  53144.74  11254.88
Fontanería                    373223.88  -5622.34
Herramientas                  995158.41  41020.34
Herramientas automotrices     502109.29  63330.22
Herramientas de jardinería    648879.72  53202.88
Iluminación                   275229.53  20264.54
Macetas                       696044.18  33941.85
Materiales de paisajismo      150552.49  -1912.37
Materiales de revestimiento   629656.36 -28869.01
Muebles de exterior           328932.27  26784.59
Neumáticos                   1022428.97  67460.05
Pesticidas                    244956.04  53343.89
Piezas de repuesto            486907.94  91148.67
Semillas                       39979.75   8865.09

In [16]:
estilo_02 = product_type.style
# estilo_02 = estilo_02.format({'Ventas': '${:,.2f}', 'Ganancia': '${:,.2f}'})
estilo_02 = estilo_02.format('USD {:,.2f}').highlight_max(color='lightgreen').highlight_min(color='red')
estilo_02

In [17]:
estilo_02.background_gradient(cmap='Greens', axis=0)        # cmap='RdYlGn'

In [18]:
#encabezado = estilo_02.set_caption('Tabla de ventas y ganancias por tipo de producto')

encabezado = {
    'selector': 'th',
    'props': [
        ('font-size', '16px'),
        ('background-color', 'None'),
        ('color', 'black'),
        ('text-align', 'right'),
        ('font-weight', 'bold'),
        ('padding', '5px'),
        ('text-transform', 'capitalize'),
        ('font-family', 'Arial')
    ]
    
}
estilo_02.set_table_styles([encabezado], overwrite=False)

# Mision 3: Equipo de Logistica
> 
> Se necesita construir una visualizacion que nos permita entender __la distribucion de pedidos por region en Argentina__.
---

In [19]:
import numpy as np

region = pd.DataFrame(df_01['region']).value_counts().to_frame().reset_index()
region.columns = ['Region', 'Num pedidos']
region.set_index('Region', inplace=True)
region

              Num pedidos
Region
Buenos Aires         2822
Litoral              1924
Norte                1555
Central              1276
Cuyo                  915
Patagónica            448

In [20]:
# porcentaje = region['Num pedidos'] / region['Num pedidos'].sum() * 100
# region['Porcentaje'] = porcentaje.round(2)
# region

In [21]:
porcentaje = region['Num pedidos'].to_numpy()
porcentaje = porcentaje / np.sum(porcentaje) * 100
region['Porcentaje'] = porcentaje.round(2)
region

              Num pedidos  Porcentaje
Region
Buenos Aires         2822       31.57
Litoral              1924       21.52
Norte                1555       17.39
Central              1276       14.27
Cuyo                  915       10.23
Patagónica            448        5.01

In [22]:
estilo_03 = region.style
estilo_03

In [27]:
encabezado_03 = {
    'selector': 'th',
    'props': [
        ('background-color', 'white'),
        ('color', 'black'),
        ('font-family', 'Arial'),
        ('font-size', '16px'),
        ('font-weight', 'bold'),
        ('text-align', 'right'),
        ('text-transform', 'capitalize'),
        ('padding', '5px')
    ]
}
celdas_03 = {
    'selector': 'td',
    'props': [
        ('background-color', 'white')
    ]
}

In [28]:
estilo_03.set_table_styles([encabezado_03, celdas_03])

In [39]:
estilo_03.format({'Porcentaje': '{:,.2f}%'})\
    .bar(subset='Porcentaje',vmin=0, vmax=100, color='#4494DA')
estilo_03

# Mision 4: Equipo Logistica
> 
> Se debe replantear la estructura y organizacion de provisionamiento de productos, para esto, se solicita la creacion de una visualizacion que permita identificar el estandar de __la cantidad de productos solicitados por mes por departamento__.
---

In [40]:
meses = df_01.copy()
meses = meses.sort_values(by='fecha_pedido', ascending=True)
meses

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
7171,2016-01-04,Entrega estándar,Ramiro Guzmán,B2C,Rosario,Santa Fe,Litoral,Jardinería y paisajismo,Pesticidas,55.92,2,9.44
651,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,12.04,2,-9.32
650,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Macetas,927.30,3,-110.13
649,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Semillas,40.08,3,7.26
1576,2016-01-06,Entrega estándar,Florencia Chávez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Jardinería y paisajismo,Decoración de jardín,66.42,3,8.31
...,...,...,...,...,...,...,...,...,...,...,...,...
796,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,179.43,3,33.63
795,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Automotriz,Neumáticos,309.19,7,4.69
794,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,1098.68,4,20.60
1151,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,47.28,2,7.68
1152,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,70.44,2,11.00

In [42]:
meses['mes'] = meses['fecha_pedido'].dt.strftime('%Y - %b')
meses = meses.reset_index(drop=True)
meses

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia,mes
0,2016-01-04,Entrega estándar,Ramiro Guzmán,B2C,Rosario,Santa Fe,Litoral,Jardinería y paisajismo,Pesticidas,55.92,2,9.44,2016 - ene.
1,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,12.04,2,-9.32,2016 - ene.
2,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Macetas,927.30,3,-110.13,2016 - ene.
3,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Semillas,40.08,3,7.26,2016 - ene.
4,2016-01-06,Entrega estándar,Florencia Chávez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Jardinería y paisajismo,Decoración de jardín,66.42,3,8.31,2016 - ene.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,179.43,3,33.63,2019 - dic.
8936,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Automotriz,Neumáticos,309.19,7,4.69,2019 - dic.
8937,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,1098.68,4,20.60,2019 - dic.
8938,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,47.28,2,7.68,2019 - dic.
8939,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,70.44,2,11.00,2019 - dic.

In [45]:
ventas_mes = meses.pivot_table(index=meses['departamento'], columns='mes', values='cantidad', aggfunc='sum', sort=False)
ventas_mes

mes,2016 - ene.,2016 - feb.,2016 - mar.,2016 - abr.,2016 - may.,2016 - jun.,2016 - jul.,2016 - ago.,2016 - sep.,2016 - oct.,...,2019 - mar.,2019 - abr.,2019 - may.,2019 - jun.,2019 - jul.,2019 - ago.,2019 - sep.,2019 - oct.,2019 - nov.,2019 - dic.
departamento,,,,,,,,,,,,,,,,,,,,,
Jardinería y paisajismo,161,87,277,323,270,273,348,339,549,276,...,458,415,542,490,423,561,929,617,946,989
Automotriz,45,20,46,107,81,83,91,95,154,85,...,167,87,150,170,168,136,280,205,331,252
Materiales de construcción,60,23,102,69,91,114,104,101,182,94,...,107,131,172,151,162,132,282,213,312,395

In [46]:
estilo_04 = ventas_mes.style
estilo_04

In [52]:
estilo_04.set_sticky(axis='index')
# '''
# Para fijar las columnas
# estilo_app.set_sticky(axis=1)
# estilo_app.set_sticky(axis='columns')
# '''

In [67]:
columnas = {
    'selector': '.col_header',
    'props': 'font-family: Arial; font-weight: normal'
}

tabla = {
    'selector': '.td,th',
    'props': 'text-align: left'
}

index = {
    'selector': '.index.name',
    'props': 'text-align: right; font-family: Arial; font-weight: bold'
}

In [66]:
estilo_04.set_table_styles([columnas, tabla, index], overwrite=False)

# Mision 5: Informe de Desempeno
> 
> El informe de desempeno es un documento importante para la empresa. En este, todos los que trabajan en la tienda pueden entender como se encuetra el estado actual de la empresa. Debdio a esto. las tablas bien construidas son esenciales para mostrar los datos de la mejor forma.
> 
> Se necesita construir una visualizacion que permita endener ___la relacion entre tipos de clientes y modo de envio de productos de acuerdo con las ventas___. De esta forma, se podra destacar en el informe cual es el modo de envio y cuales son los que mas generaron lucro en las ventas.
---

In [76]:
df_clientes = df_01.pivot_table(index='segmento_cliente', columns='modo_envio', values='ventas', aggfunc='sum', sort=False)
df_clientes

modo_envio,Económica,Entrega estándar,Envío rápido,Entrega en 24 horas
segmento_cliente,,,,
B2C,729174.73,2248283.69,498294.88,182531.47
B2B,718461.22,1884738.56,602049.40,217465.60

In [77]:
df_clientes['Total'] = df_clientes.sum(axis=1).round(2)     # Columna total
df_clientes.loc['Total'] = df_clientes.sum().round(2)       # Fila total
df_clientes

modo_envio,Económica,Entrega estándar,Envío rápido,Entrega en 24 horas,Total
segmento_cliente,,,,,
B2C,729174.73,2248283.69,498294.88,182531.47,3658284.77
B2B,718461.22,1884738.56,602049.40,217465.60,3422714.78
Total,1447635.95,4133022.25,1100344.28,399997.07,7080999.55

In [78]:
estilo_05 = df_clientes.style.format('{:,.2f}')
estilo_05

In [85]:
tabla = {
    'selector': 'td,th:not(.index_name)',
    'props': 'text-align: center; font-family: Arial; font-weight: normal; background-color: white'
}

index = {
    'selector': '.index_name',
    'props': 'text-align: right; font-style: italic; font-family: Arial; font-weight: normal; color: #4494DA; background-color: white'
}

estilo_05.set_table_styles([tabla, index], overwrite=False)

In [95]:
estilo_05.set_table_styles({
    'Total': [
        {'selector': 'td',
         'props': 'border-top: 2px solid #4494DA'}
        ,{'selector': 'th',
         'props': 'border-top: 2px solid #4494DA'}
    ],
    'B2C': [
        {'selector': 'td',
         'props': 'border-top: 2px solid #4494DA'}
        ,{'selector': 'th',
         'props': 'border-top: 2px solid #4494DA'}
    ]
}, overwrite=False, axis=1)

In [97]:
estilo_05.set_table_styles({
    'Total': [
        {'selector': '.true',
         'props': 'background-color: #E5E5E5; color: #4494DA'}
    ]
}, overwrite=False, axis=0)

colores_columna = pd.DataFrame(['false','true','false'], index=df_clientes['Total'].index, columns=['Total'])

estilo_05.set_td_classes(colores_columna)